🔀 :: (ENTRY-160) feed service url수정
EntryDSM/Equus-Feed pull request #34
Opened 2024-04-09 13:23 UTC by rudeh2926

API DOCS보고 URL과 API를 수정하였습니다

<img width="930" alt="스크린샷 2024-04-09 오후 10 22 22" src="https://github.com/EntryDSM/Equus-Feed/assets/125863754/420ce334-4208-4366-8b58-a19ca5156c30">
<img width="664" alt="스크린샷 2024-04-09 오후 10 22 43" src="https://github.com/EntryDSM/Equus-Feed/assets/125863754/ac91e166-f8c9-4911-99c3-d2b0bcdc080c">

2024-04-09 13:32 UTC, HyunSu1768 approved these changes

2024-04-10 12:58 UTC, lilseongwon requested changes

2024-04-10 12:58 UTC, lilseongwon commented on src/main/kotlin/hs/kr/equus/feed/domain/notice/domain/Notice.kt
> +    @Column(name = "admin_name", nullable = false, columnDefinition = "BINARY(16)")
이거 컬럼 왜 admin_name이에요? admin_id 아닌가요?

2024-04-10 13:25 UTC, rudeh2926 commented on src/main/kotlin/hs/kr/equus/feed/domain/notice/domain/Notice.kt
> +    @Column(name = "admin_name", nullable = false, columnDefinition = "BINARY(16)")
https://github.com/EntryDSM/Equus-Feed/commit/094dd1c70f34d99be1243f89556ce24e01154a82
변경하겠습니다

2024-04-11 04:45 UTC, lilseongwon approved these changes

2024-04-11 05:34 UTC, merged