🔀 :: (ENTRY-190) 공지사항 생성, 상세조회 api 로직 변경하기
EntryDSM/Equus-Feed pull request #45
Opened 2024-06-10 10:59 UTC by rudeh2926

생성
<img width="777" alt="스크린샷 2024-06-10 오후 7 57 30" src="https://github.com/EntryDSM/Equus-Feed/assets/125863754/ca5784cd-1833-48f0-8086-01d313d939ac">
상세조회
<img width="783" alt="스크린샷 2024-06-10 오후 7 57 20" src="https://github.com/EntryDSM/Equus-Feed/assets/125863754/1ee986b7-7a69-40cd-9812-333b796e66dd">

2024-06-11 01:15 UTC, HyunSu1768 commented on src/main/kotlin/hs/kr/equus/feed/domain/notice/service/GetNoticeService.kt
> +        val attachFileUrls = notice.attachFile!!.split(",").map { fileUtil.generateObjectUrl(it, PathList.NOTICE) }
Notice 에 attachFile 은 nullable 인데 여기서는 어떻게 null 단언이 되죠?

2024-06-11 01:16 UTC, HyunSu1768 commented on src/main/kotlin/hs/kr/equus/feed/infrastructure/s3/util/FileUtil.kt
> +            )
EXP를 지운 이유는 무엇인가요?

2024-06-11 01:18 UTC, HyunSu1768 requested changes

2024-06-11 01:18 UTC, HyunSu1768 commented on src/main/kotlin/hs/kr/equus/feed/global/config/AwsConfig.kt
>      @Value("\${cloud.aws.region.static}")
secretKey에서 secret-key 로 바꾼 이유는 무엇인가요?

2024-06-11 01:23 UTC, rudeh2926 commented on src/main/kotlin/hs/kr/equus/feed/infrastructure/s3/util/FileUtil.kt
> +            )
안지우게 되면 공지사항에 올린 사진이 일정 시간이 지우면 보이지 않습니다

2024-06-11 01:23 UTC, rudeh2926 commented on src/main/kotlin/hs/kr/equus/feed/global/config/AwsConfig.kt
>      @Value("\${cloud.aws.region.static}")
cloudconfig에 맞게 변경하였습니다

2024-06-11 01:26 UTC, HyunSu1768 commented on src/main/kotlin/hs/kr/equus/feed/global/config/AwsConfig.kt
>      @Value("\${cloud.aws.region.static}")
feed-dev 에는 secretKey 가 맞을텐데용

2024-06-11 01:31 UTC, HyunSu1768 commented on src/main/kotlin/hs/kr/equus/feed/infrastructure/s3/util/FileUtil.kt
> +            )
presignedurl 은 기본적으로 지정해 주는 exp time이 있어도 이렇게 해도 영구적으로 보이진 않을겁니다.

근데 어차피 조회할때 마다 url 생성해줘서 일정 시간이 지나도 새로고침 하면 새로운 url 생성돼서 다시 보여질 수 있는거 아닌가요?
EXP 를 늘려주는 방안은 생각 안해보셨나요?

2024-06-11 02:00 UTC, rudeh2926 commented on src/main/kotlin/hs/kr/equus/feed/infrastructure/s3/util/FileUtil.kt
> +            )
시간을 늘리겠습니다

2024-06-11 02:00 UTC, rudeh2926 commented on src/main/kotlin/hs/kr/equus/feed/global/config/AwsConfig.kt
>      @Value("\${cloud.aws.region.static}")
아 제 로컬 config랑 dev랑 다르네요. 변경하겠습니다

2024-06-11 06:42 UTC, rudeh2926 commented on src/main/kotlin/hs/kr/equus/feed/domain/notice/service/GetNoticeService.kt
> +        val attachFileUrls = notice.attachFile!!.split(",").map { fileUtil.generateObjectUrl(it, PathList.NOTICE) }
변경했습니다

2024-06-11 23:43 UTC, HyunSu1768 approved these changes

2024-06-12 04:51 UTC, lilseongwon commented on src/main/kotlin/hs/kr/equus/feed/infrastructure/s3/util/FileUtil.kt
> +            )
그리고 EXP 안쓸거면 url 저장하는 게 맞습니다. fileName을 왜 저장하는지를 숙지하고 개발하면 좋을 것 같습니다.

2024-06-12 05:04 UTC, lilseongwon commented on src/main/kotlin/hs/kr/equus/feed/infrastructure/s3/util/FileUtil.kt
> +            )
제가 잘 이해한 건지 모르겠는데, 모두 같은 generateObjectUrl 메서드를 사용하는데 '증명사진은 EXP가 짧아야 되고, 공지사항은 굳이 만료시간이 필요 없다' 라면 어떻게 해결하면 좋을지에 대해 한 번 생각정도는 하는게 좋을 것 같아요.

가장 직관적인 방법으론 유형별 사진 경로와 만료일을 다음과 같이
enum class FileInfo(
    val path: String,
    val exp: Int
) {
    PHOTO(
        path = "photopath",
        exp = 1000
    )
}
이런식으로 만들면 유형마다 경로와 만료일을 다르게 가져갈 수 있고, S3Util에는 해당 enum값을 파라미터로 받으면 해결 가능하지 않을까 생각해봤습니다. 항상 하나만 말고 여러 방식을 구상해보고, 트레이드 오프를 통해 최선의 방법으로 문제를 해결하는 개발자로 성장하길 바라는 맘에 한번 글을 써봅니다..ㅎㅎ

2024-06-12 05:10 UTC, lilseongwon requested changes

2024-06-12 05:10 UTC, lilseongwon commented on src/main/kotlin/hs/kr/equus/feed/domain/notice/domain/Notice.kt
> +
여기서 굳이 String값으로 첨부파일을 저장하는 이유는 뭔가요?
List<String>으로 저장하면 되는 거 아닌가요?

2024-06-12 05:39 UTC, rudeh2926 commented on src/main/kotlin/hs/kr/equus/feed/infrastructure/s3/util/FileUtil.kt
> +            )
증명사진은 application에 있는거 아닌가요?

2024-06-12 05:39 UTC, rudeh2926 commented on src/main/kotlin/hs/kr/equus/feed/infrastructure/s3/util/FileUtil.kt
> +            )
> 그리고 EXP 안쓸거면 url 저장하는 게 맞습니다. fileName을 왜 저장하는지를 숙지하고 개발하면 좋을 것 같습니다.

넵

2024-06-12 05:44 UTC, rudeh2926 commented on src/main/kotlin/hs/kr/equus/feed/domain/notice/domain/Notice.kt
> +
변경하겠습니다

2024-06-12 05:51 UTC, lilseongwon commented on src/main/kotlin/hs/kr/equus/feed/infrastructure/s3/util/FileUtil.kt
> +            )
> 증명사진은 application에 있는거 아닌가요?

예를 든 겁니다..ㅎㅎ

2024-06-12 07:28 UTC, lilseongwon commented on src/main/kotlin/hs/kr/equus/feed/domain/notice/domain/Notice.kt
> +
attachFile 엔티티 만들고 OneToMany로 묶으십쇼

2024-06-12 10:05 UTC, rudeh2926 commented on src/main/kotlin/hs/kr/equus/feed/infrastructure/s3/util/FileUtil.kt
> +            )
죄송합니다

2024-06-17 14:17 UTC, HyunSu1768 approved these changes

2024-06-18 08:19 UTC, rudeh2926 commented on src/main/kotlin/hs/kr/equus/feed/domain/notice/domain/Notice.kt
> +
https://github.com/EntryDSM/Equus-Feed/pull/45/commits/225a33c7be36d7195e89b702d37a3bd79e2b728f

2024-06-19 13:05 UTC, lilseongwon approved these changes

2024-06-19 13:05 UTC, lilseongwon commented on src/main/kotlin/hs/kr/equus/feed/domain/notice/domain/Notice.kt
> +    var attachFile: List<AttachFile>? = emptyList(),
이거 왜 nullable이에요?

2024-06-19 13:07 UTC, lilseongwon commented on src/main/kotlin/hs/kr/equus/feed/domain/notice/service/CreateNoticeService.kt
> +        }
이것도 왜 null?

2024-06-19 13:07 UTC, lilseongwon commented on src/main/kotlin/hs/kr/equus/feed/domain/notice/presentation/dto/request/CreateNoticeRequest.kt
> +    val attachFileName: List<String>? = null
이것도 왜 null?

2024-06-19 13:31 UTC, rudeh2926 commented on src/main/kotlin/hs/kr/equus/feed/domain/notice/presentation/dto/request/CreateNoticeRequest.kt
> +    val attachFileName: List<String>? = null
첨부파일이 입력받을 때 널일 수 있기때문에 널로 했습니다

2024-06-19 13:31 UTC, rudeh2926 commented on src/main/kotlin/hs/kr/equus/feed/domain/notice/service/CreateNoticeService.kt
> +        }
첨부파일이 입력받을 때 널일수 있기때문에 했습니다

2024-06-19 14:25 UTC, rudeh2926 commented on src/main/kotlin/hs/kr/equus/feed/domain/notice/domain/Notice.kt
> +    var attachFile: List<AttachFile>? = emptyList(),
첨부파일이 꼭 있어야하는건 아니기 때문입니다

2024-06-19 14:29 UTC, merged